### ISSUE TITLE
SPHINX Update and migrate to jessie/stretch?

### ISSUE THREAD

**Issue by ponceta** [geoadmin/service-sphinxsearch#191]
Small problem here with multiple target wordforms which are not accepted with the current version

http://sphinxsearch.com/docs/current.html#conf-wordforms

`Starting with version 2.2.4, you can specify multiple destination tokens:`

Is it complicated to update sphinx? Because it's already on 2.2.7 and we are still on 2.1.5!

**Comment by loicgasser** [comment]
Hi, we would need to ask Cédric Janneret for that as we don't have root access on this instance.
We should probably create a new test instance and install our current project to test the new versionof sphinxsearch.

Could you check what is the latest debian package for sphinxsearch. Because I think this is also a limiting factor. We can probably discuss it next week during "Teamsitzung".

**Comment by ponceta** [comment]
http://sphinxsearch.com/downloads/release/

2.2.7-release is the actual version.

**Comment by gjn** [comment]
2.3.2 is current releas.

We should also migrate from wheezy to jessie or stretch.
