### ISSUE TITLE
Update trigger don't work anymore

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-sphinxsearch#213]
make deploy-int-config db=kogis_dev.bfs.adressen_sphinx

should update all the indices associated to this table but instead we get:

updating sphinx indexes, using database pattern: kogis_dev
no sphinx indexes are using the database pattern kogis_dev

Any idea? I can also provide a fix but you might be faster on this one.

**Comment by ltclm** [comment]
Hi Loic

I dont think there is an issue.
1. on sphinx int the database used for the db pattern / index generation should be kogis_int instead of kogis_dev
2. In the db parameter you have entered a view, views cannot be deployed and therefore cannot trigger an index update

You should use:
```bash
make deploy-int-config db=kogis_int.bfs.adr
```

The deploy script will execute the following command on sphinx integration
```bash
sphinxsearch@ip-10-220-4-39 (vpc/sphinxsearch - integration):~$ python /etc/sphinxsearch/pg2sphinx_trigger.py -d kogis_int.bfs.adr -c list
4 indexes are using the database pattern: kogis_int.bfs.adr
      address -> kogis_int
      address_metaphone -> kogis_int
      address_soundex -> kogis_int
      ch_bfs_gebaeude_wohnungs_register -> kogis_int

```
